### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/postcss-ant#7]
- [ ] clear floats
- [ ] rounders should be able to accept 1. e.g `rounder(100vh)` errs
- [ ] should be able to repeat last size set
- [ ] should be able to set `rows(100px all)` or something similar (work on syntax)
- [ ] `columns(1/4)` can assume cycle 4
- [ ] allow `sizes/pluck` to work from within `bump()`
